[package]
name = "rt-wasmer"
edition = "2024"
resolver = "2"
publish = false

[lib]
path = "lib.rs"

[dependencies]
benchmark-utils = { workspace = true }
wasmer = { workspace = true }
wasmer-compiler-singlepass = { workspace = true }
wasmer-compiler-cranelift = { workspace = true }
